<?php

namespace App\Filament\Resources\SubscriptionResource\Pages;

use App\Filament\Resources\SubscriptionResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditSubscription extends EditRecord
{
    protected static string $resource = SubscriptionResource::class;

    public function __construct($id = null)
    {
        parent::__construct($id);
    }

    protected function getActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function handleRecordUpdate(Model $record, array $data): Model
    {
        $this->redirect(SubscriptionResource::getUrl('edit', ['record' => $record->id]));
        return parent::handleRecordUpdate($record, $data); // TODO: Change the autogenerated stub
    }
}
