<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

#[OA\Schema(
    schema: 'LoginCodeRequest',
    title: 'LoginCodeRequest',
    required: ['user_id', 'lector_id', 'content']
)]
class LoginCodeRequest extends FormRequest
{
    #[OA\Property(property: 'code', description: 'email пользователя', type: 'string')]
    #[OA\Property(property: 'device_name', description: 'пароль пользователя', type: 'string')]
    public function rules(): array
    {
        return [
            'code' => 'required|string|exists:login_codes',
            'device_name' => 'sometimes|string'
        ];
    }

    protected function failedValidation(Validator $validator)
    {
        \Log::error("фэйлед валидэйшен: $this->code");
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
