<?php

namespace Auth;

use App\Models\LoginCode;
use App\Models\User;
use Illuminate\Testing\Fluent\AssertableJson;
use Symfony\Component\HttpFoundation\Response;
use Tests\TestCase;

class LoginCodeTest extends TestCase
{
    private ?User $user = null;
    private ?LoginCode $loginCode = null;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->loginCode = LoginCode::create([
            'email' => $this->user->email,
            'code' => mt_rand(100000, 999999)
        ]);
    }

    public function testMethod()
    {
        $response = $this->get(route('v1.login.code'));
        $this->assertEquals(405, $response->getStatusCode());
    }

    public function testSuccess()
    {
        $response = $this->postJson(route('v1.login.code'), [
            'email' => $this->user->email,
            'code' => (string) $this->loginCode->code
        ]);

        $response
            ->assertStatus(Response::HTTP_OK)
            ->assertJson(function (AssertableJson $json) {
                $json->hasAll(['user', 'access_token', 'refresh_token', 'token_type']);
            });
    }
}
