<?php

namespace App\Filament\Resources\ThreadResource\Pages;

use App\Filament\Resources\ThreadResource;
use App\Models\Threads\Thread;
use Filament\Pages\Actions\DeleteAction;
use Filament\Resources\Pages\EditRecord;

class EditThread extends EditRecord
{
    protected static string $resource = ThreadResource::class;

    protected function getActions(): array
    {
        return [
            DeleteAction::make(),
        ];
    }

    public function hasCombinedRelationManagerTabsWithForm(): bool
    {
        return true;
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $threadId = $data['id'];
        $thread = Thread::find($threadId);
        $thread->participants()->updateOrCreate(['user_id' => auth()->id()], ['read_at' => now()]);

        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }
}
